### ISSUE TITLE
Missing column `splittransactionid`

### ISSUE THREAD

**Issue by imjuzcy** [dreautall/bluecoins-to-fireflyiii#9]
```
{'data': {'api_version': '2.0.13',
          'driver': 'pgsql',
          'os': 'Linux',
          'php_version': '8.3.4',
          'version': '6.1.13'}}
Traceback (most recent call last):
  File "/home/ubuntu/firefly_iii/bluecoins-to-fireflyiii/./convert.py", line 89, in <module>
    total_txs = db.query_transactions_count()
  File "/home/ubuntu/firefly_iii/bluecoins-to-fireflyiii/db.py", line 79, in query_transactions_count
    res = cur.execute(sql)
sqlite3.OperationalError: no such column: splittransactionid
```
The `fydb` file is from the new Bluecoins after the redesign, version 13.0.153. New database structure, perhaps? The available column names in my `fydb` file in the `TRANSACTIONSTABLE` table are:
```
transactionsTableID
itemID
amount
transactionCurrency
conversionRateNew
date
transactionTypeID
categoryID
accountID
notes
status
accountReference
accountPairID
uidPairID
deletedTransaction
newSplitTransactionID
transferGroupID
reminderTransaction
reminderGroupID
reminderFrequency
reminderRepeatEvery
reminderEndingType
reminderStartDate
reminderEndDate
reminderAfterNoOfOccurences
reminderAutomaticLogTransaction
reminderRepeatByDayOfMonth
reminderExcludeWeekend
reminderWeekDayMoveSetting
reminderUnbilled
creditCardInstallment
reminderVersion
dataExtraColumnString1
```

**Comment by imjuzcy** [comment]
This is using v1.0.0 of `bluecoins-to-fireflyiii`

**Comment by dreautall** [comment]
Hi, I'm sorry - I'm not using Bluecoins anymore (obviously). I can just assume the column got renamed to "newSplitTransactionID" - you might try to just replace it 1:1 in the code and see if it works. Other than that I cannot really provide support, sorry :(

**Comment by imjuzcy** [comment]
Alright, that's understandable. I'll play around and see if it works and give an update here.

**Comment by imjuzcy** [comment]
Here's a `git diff` that made it work if someone else wants to use this tool:
```
diff --git a/db.py b/db.py
index 7736e95..7008960 100644
--- a/db.py
+++ b/db.py
@@ -34,7 +34,7 @@ class bluecoinsDB:
             "   GROUP_CONCAT(categoryID) AS categoryIDs, "
             "   GROUP_CONCAT(accountID) as accountIDs, "
             "   GROUP_CONCAT(notes, CHAR(0x1D)) as notes, "
-            "   IFNULL(CASE WHEN newsplittransactionid IS 0 THEN NULL ELSE newsplittransactionid END, splittransactionid) AS mergedSplitTransactionID, "
+            "   (CASE WHEN newsplittransactionid IS 0 THEN NULL ELSE newsplittransactionid END) AS mergedSplitTransactionID, "
             "   (SELECT GROUP_CONCAT(labelName) FROM LABELSTABLE WHERE transactionIDLabels = transactionsTableID GROUP BY transactionIDLabels) AS labelNames, "
             "   (SELECT GROUP_CONCAT(pictureFileName) FROM PICTURETABLE WHERE transactionID = transactionsTableID GROUP BY transactionID) AS pictureFileName "
             "FROM "
@@ -46,7 +46,7 @@ class bluecoinsDB:
             f"  AND transactionTypeID IN ({DB_CONFIG['TRANSACTION_DEPOSIT']},{DB_CONFIG['TRANSACTION_WITHDRAWAL']}) "
             "   AND deletedTransaction = 6 "
             "GROUP BY "
-            "   IFNULL(IFNULL(CASE WHEN newsplittransactionid IS 0 THEN NULL ELSE newsplittransactionid END, splittransactionid), transactionstableid) "
+            "   IFNULL(CASE WHEN newsplittransactionid IS 0 THEN NULL ELSE newsplittransactionid END, transactionstableid) "
             "ORDER BY "
             "   date DESC, transactionsTableID ASC "
         )
@@ -69,9 +69,7 @@ class bluecoinsDB:
             "           AND deletedTransaction = 6 "
             "       GROUP BY "
             "           IFNULL( "
-            "              IFNULL( "
-            "                   CASE WHEN newsplittransactionid IS 0 THEN NULL ELSE newsplittransactionid END, "
-            "              splittransactionid), "
+            "              CASE WHEN newsplittransactionid IS 0 THEN NULL ELSE newsplittransactionid END, "
             "           transactionstableid) "
             "   )"
         )
```

**Comment by dreautall** [comment]
thank you, patched the file!
